services:
  db:
    image: supabase/postgres:15.1.0.98
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  studio:
    image: supabase/studio:20240109-2f93816
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      SUPABASE_URL: http://rest:3000
      SUPABASE_ANON_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiYW5vbiIsImlhdCI6MTY5ODg4ODg4OH0.0RwBDOLQZXrhiwfwlihtz8aMKYN-LFtcU5UJ5dP47sY
      SUPABASE_SERVICE_ROLE_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoic2VydmljZV9yb2xlIiwiaWF0IjoxNjk4ODg4ODg4fQ.qyHRaUwsMnXYntUm5hcfLUj5rBdT4vZ6es-Bu9VqNlI
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres

  rest:
    image: postgrest/postgrest:v11.2.0
    restart: always
    depends_on:
      - db
    environment:
      PGRST_DB_URI: postgres://postgres:postgres@db:5432/postgres
      PGRST_DB_ANON_ROLE: anon
      PGRST_JWT_SECRET: supersecretjwtkeyyoushouldchange!
    ports:
      - "3001:3000"

  auth:
    image: supabase/gotrue:v2.142.0
    restart: always
    depends_on:
      - db
    environment:
      GOTRUE_SITE_URL: http://localhost:3000
      GOTRUE_API_HOST: 0.0.0.0
      GOTRUE_API_PORT: 9999
      GOTRUE_DB_DRIVER: postgres
      GOTRUE_DB_DATABASE_URL: postgres://postgres:postgres@db:5432/postgres
      GOTRUE_JWT_SECRET: supersecretjwtkeyyoushouldchange!
      GOTRUE_JWT_EXP: 3600
      GOTRUE_ANON_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiYW5vbiIsImlhdCI6MTY5ODg4ODg4OH0.0RwBDOLQZXrhiwfwlihtz8aMKYN-LFtcU5UJ5dP47sY
      GOTRUE_SERVICE_ROLE_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoic2VydmljZV9yb2xlIiwiaWF0IjoxNjk4ODg4ODg4fQ.qyHRaUwsMnXYntUm5hcfLUj5rBdT4vZ6es-Bu9VqNlI
    ports:
      - "9999:9999"

  realtime:
    image: supabase/realtime:v2.32.8
    restart: always
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres
      PORT: 4000
      JWT_SECRET: supersecretjwtkeyyoushouldchange!
    ports:
      - "4000:4000"

  storage:
    image: supabase/storage-api:v0.46.7
    restart: always
    depends_on:
      - db
    environment:
      ANON_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiYW5vbiIsImlhdCI6MTY5ODg4ODg4OH0.0RwBDOLQZXrhiwfwlihtz8aMKYN-LFtcU5UJ5dP47sY
      SERVICE_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoic2VydmljZV9yb2xlIiwiaWF0IjoxNjk4ODg4ODg4fQ.qyHRaUwsMnXYntUm5hcfLUj5rBdT4vZ6es-Bu9VqNlI
      POSTGREST_URL: http://rest:3000
      DATABASE_URL: postgres://postgres:postgres@db:5432/postgres
    ports:
      - "5000:5000"

volumes:
  db_data:
